name: OSV-Scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Weekly Monday 06:00 UTC.
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  scan:
    name: OSV-Scanner V2
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8deb546fdb875b9996d27d4950be7312dac076a1 # v2.5.0
    permissions:
      contents: read
      security-events: write
      actions: read
    with:
      scan-args: |-
        --recursive
        --skip-git
        ./
      upload-sarif: true
